---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - release
  schedule:
    - cron: '0 1 * * *'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test:ci
        env:
          CI: true
      - name: save coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
      - name: build
        run: yarn build
      - name: build docs
        if: github.ref == 'refs/heads/release'
        run: yarn docs
      - name: save docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs
  docs:
    needs: ci
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: download docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: ./docs
      - name: publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
  coverage:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: download coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: ./coverage
      - name: upload coverage
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  create-release-pull-request:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - run: |
          git fetch origin main:main
          git reset --hard main
      - name: create release pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          title: Publish release
          base: release
  release:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    steps:
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build
      - name: release
        run: yarn semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
  approve-renovate:
    runs-on: ubuntu-latest
    needs: ci
    # if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            await github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.number,
              event: 'APPROVE',
            })
